# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/gitevanhsu"

[social.params]
icon = "brand-github"

# [[social]]
# identifier = "linkedin"
# name = "Linkedin"
# url = "https://www.linkedin.com/in/yang-min-hsu"

# [social.params]
# icon = "brand-linkedin"